### ISSUE TITLE
Which image am I using?

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/researchdelight-image#1]
When developing a new image and pushing it to quay.io , it get's assigned a new tag.  Is it possible to tell, from within JupyterHub, which specific image/tag is being used by each user?  

Can the user determine this on their own?

This comes up because it is not always obvious if JupyterHub is using the 'new' image or the 'previous' image.

**Comment by yuvipanda** [comment]
You can look at the JUPYTER_IMAGE environment variable to determine this

**Comment by damianavila** [comment]
Closing as answered, please reopen if you disagree.
